### ISSUE TITLE
Page returns a 404

### ISSUE THREAD

**Issue by dackyD** [pencilblue/jennifer#4]
Hi guys,

Making a page and hooking it up on a navigation menu returns a 404.
http://localhost:8080/page/555ee996ba04667a03f9ce5f => 404 page cannot be found.

Harvey

**Comment by blakecallens** [comment]
Is the page published or a draft?

**Comment by dackyD** [comment]
It's published.

**Comment by blakecallens** [comment]
DAO object was null when attempting to pull based on ObjectID.
